language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
after_success: npm install nyc | npm run coverage
env:
  global:
    secure: UbIb31nxyWqfmXB+kcI9B7YL0hkN3i2rep3Ha3PTyi/J27DSFdFikQjXHanyf0laYkiw7yFgeO0KPeg1GOY+bWkNbo8QIt62+GaPHgEHYkPPQU5KKbNIDIdaRtXoMNwvXrC8LF8UHl6vWGP1muHsO/2Cd8aMKBNjit/YDATuX83ui9CgYZoKk+v/+pN728+/n05c3HPkG94U+iPq/x9XWVcMiGEgWxc29jXw8cdviu74hFrHrRtgJWrC0zJs01Asczr0ljteY0PKGE4HMu2WxnYIVPyGIarKMzVlbku5gnnEnIrac7lY8iWvfiWx7hMcSdKQfJXAKA2OM1rV6wB5RMlV5nhaUU7QMHIcRZjMDSTk53xAgM2JfuC9838/o4eWnIxy0FdXygijWThPJmWEa0jokzAG5viNne8PTb4ivsOvo3/4soaAvIUXLbUKFGV35AjzpyI54fo+2EZf3fKqEp4WDP17W2zjbnNIS/AS21R3RjoOMHDmP65rbxuvFnL0dj6ah0ZWA65Motg0SDDq0MzENNtLHMNYa9zFZsX2OP/YIwd37IdCqsRv4CPb3/gkrAhvR6JLBucxuESutB2566YCHjZ2EsHV7kxRZZS1tqPV2uvANqhceZftTSyYHRcYpAYLpEnUn0FomJj1nhJb6317ebhbUqn3OphYIK1YvX8=
