language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
branches:
  only:
  - master
  - development
after_success: npm run coverage
env:
  global:
    secure: HB+wy/57S2wIet0i3OA2ZRI1o+dY48EJCMOLanXgsERVuvjA6Z2fJ6ozOyc4Gn3rNgyiUO9l40Lr4Vv7xhtXuyOy2hDGcY37l+WKXfnyrG8Ka+UH1vr4mzNRbEo7wes2iESyt0EznFmhLoPNqJCpXBFiiJUE9/ISv74mPP59j2qSCHUdviWzLaeo1a5hZhQhCCm+aI1QYA1ajMbVo8J3WH1GHAylYTAY49zBPpyRUhQXvaJOBrw/WzAZAVrnFs50ErGau29RkSvh4tpW1i8t/fdJ1B2uqCydIuXg8orv3+KyVfEZDXBUooElsGrrU3NF8SHPuEwXROwmbWi758QLaNeqG++EoxiL5EZAvZaWpt3A8jDDbXabt/+dLJLU0s/FI4qBMtxPAzBeMbJ/bO6YfMjcdohEUPdlM5EIInh0eV+gJSnS+eglqAd4D2CM6cH6tZweS9PLNM4RSutQqdFGxF0Iz97y58l6EejK2LNQ5GeNpjONoKsTZdW9P1WXMLmAHQKOW4GmZ6AnJ9GnD1cW10U6z37J7RIsxEyDeG2lW0Dv82gfcu72MozG41Vf13d26605HL+TOyQMK9LRZOn9+evJIy3ZU1xbSrb+gxZHKemjc4zB4CKsd19Rdzf/KeUmIBHJtzQY0K+7I6QvmS7ZByqRtMdMGg98n9tjrjpuBhA=
